MAPS_API_KEY=AIzaSyDEhUMedG2Gl9yOkkpIVSYUYCnCkBJOr3I

SUPABASE_URL=https://bvchtshakpvdrwrjomja.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2Y2h0c2hha3B2ZHJ3cmpvbWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNDk3OTMsImV4cCI6MjA4ODkyNTc5M30.-E740Ezx-rUDFeipTsDkibo59E5LATLbazm4kog1OUY
